"""
Candidate Database
Contains 15 Indian candidates with diverse profiles
"""

def get_candidates():
    """Return list of 15 Indian candidates with various skill profiles"""
    
    candidates = [
        {
            "id": 1,
            "name": "Arjun Sharma",
            "email": "arjun.sharma@email.com",
            "phone": "+91-98765-43210",
            "location": "Bangalore",
            "experience_years": 5,
            "current_role": "Senior Software Engineer",
            "company": "Tech Mahindra",
            "skills": ["python", "django", "react", "aws", "docker", "postgresql", "machine learning"],
            "education": "B.Tech",
            "current_salary": "18L",
            "notice_period": "30 days",
            "bio": "Passionate about building scalable web applications with 5 years of experience in Python and JavaScript frameworks. Looking for challenging roles in product companies."
        },
        {
            "id": 2,
            "name": "Priya Patel",
            "email": "priya.patel@email.com",
            "phone": "+91-98765-43211",
            "location": "Hyderabad",
            "experience_years": 7,
            "current_role": "Full Stack Developer",
            "company": "Wipro",
            "skills": ["java", "spring", "angular", "mysql", "docker", "kubernetes", "microservices"],
            "education": "M.Tech",
            "current_salary": "22L",
            "notice_period": "60 days",
            "bio": "Experienced full-stack developer with strong expertise in Java and Angular. Interested in working with emerging technologies."
        },
        {
            "id": 3,
            "name": "Rahul Verma",
            "email": "rahul.verma@email.com",
            "phone": "+91-98765-43212",
            "location": "Bangalore",
            "experience_years": 3,
            "current_role": "Software Engineer",
            "company": "Flipkart",
            "skills": ["python", "flask", "react", "mongodb", "redis", "aws"],
            "education": "B.E",
            "current_salary": "12L",
            "notice_period": "15 days",
            "bio": "Young and enthusiastic developer with expertise in Python and React. Looking for growth opportunities in e-commerce."
        },
        {
            "id": 4,
            "name": "Ananya Iyer",
            "email": "ananya.iyer@email.com",
            "phone": "+91-98765-43213",
            "location": "Chennai",
            "experience_years": 6,
            "current_role": "Data Scientist",
            "company": "TCS",
            "skills": ["python", "tensorflow", "machine learning", "data science", "sql", "tableau"],
            "education": "M.Sc",
            "current_salary": "20L",
            "notice_period": "45 days",
            "bio": "Data scientist with 6 years of experience in ML and AI. Passionate about solving complex business problems through data."
        },
        {
            "id": 5,
            "name": "Vikram Singh",
            "email": "vikram.singh@email.com",
            "phone": "+91-98765-43214",
            "location": "Pune",
            "experience_years": 8,
            "current_role": "Tech Lead",
            "company": "Infosys",
            "skills": ["java", "spring", "hibernate", "aws", "docker", "microservices", "agile"],
            "education": "B.Tech",
            "current_salary": "28L",
            "notice_period": "90 days",
            "bio": "Tech lead with 8 years of experience. Looking for leadership opportunities where I can mentor teams and drive projects."
        },
        {
            "id": 6,
            "name": "Sneha Krishnan",
            "email": "sneha.krishnan@email.com",
            "phone": "+91-98765-43215",
            "location": "Bangalore",
            "experience_years": 4,
            "current_role": "Backend Developer",
            "company": "Amazon",
            "skills": ["python", "node.js", "postgresql", "redis", "docker", "kubernetes"],
            "education": "B.E",
            "current_salary": "16L",
            "notice_period": "30 days",
            "bio": "Backend developer specializing in distributed systems. Interested in roles involving high-scale systems."
        },
        {
            "id": 7,
            "name": "Karthik Nair",
            "email": "karthik.nair@email.com",
            "phone": "+91-98765-43216",
            "location": "Kochi",
            "experience_years": 2,
            "current_role": "Junior Developer",
            "company": "Startup",
            "skills": ["javascript", "react", "node.js", "mongodb", "html", "css"],
            "education": "B.Sc",
            "current_salary": "6L",
            "notice_period": "Immediate",
            "bio": "Fresh talent with strong JavaScript skills. Looking for opportunities to learn and grow in a dynamic environment."
        },
        {
            "id": 8,
            "name": "Meera Joshi",
            "email": "meera.joshi@email.com",
            "phone": "+91-98765-43217",
            "location": "Mumbai",
            "experience_years": 5,
            "current_role": "DevOps Engineer",
            "company": "Accenture",
            "skills": ["docker", "kubernetes", "jenkins", "aws", "linux", "shell scripting"],
            "education": "B.Tech",
            "current_salary": "15L",
            "notice_period": "45 days",
            "bio": "DevOps enthusiast with expertise in CI/CD and cloud infrastructure. Looking for challenging DevOps roles."
        },
        {
            "id": 9,
            "name": "Rohan Gupta",
            "email": "rohan.gupta@email.com",
            "phone": "+91-98765-43218",
            "location": "Delhi",
            "experience_years": 9,
            "current_role": "Engineering Manager",
            "company": "Google",
            "skills": ["python", "java", "machine learning", "data engineering", "spark", "aws"],
            "education": "M.Tech",
            "current_salary": "45L",
            "notice_period": "60 days",
            "bio": "Engineering manager with 9 years of experience. Looking for senior leadership roles in product companies."
        },
        {
            "id": 10,
            "name": "Divya Menon",
            "email": "divya.menon@email.com",
            "phone": "+91-98765-43219",
            "location": "Bangalore",
            "experience_years": 4,
            "current_role": "Frontend Developer",
            "company": "Swiggy",
            "skills": ["react", "typescript", "vue", "html", "css", "javascript"],
            "education": "B.Des",
            "current_salary": "14L",
            "notice_period": "30 days",
            "bio": "Creative frontend developer with an eye for design. Interested in building beautiful user experiences."
        },
        {
            "id": 11,
            "name": "Sanjay Reddy",
            "email": "sanjay.reddy@email.com",
            "phone": "+91-98765-43220",
            "location": "Hyderabad",
            "experience_years": 6,
            "current_role": "Cloud Architect",
            "company": "Microsoft",
            "skills": ["azure", "aws", "gcp", "docker", "kubernetes", "security"],
            "education": "B.Tech",
            "current_salary": "30L",
            "notice_period": "60 days",
            "bio": "Cloud specialist with expertise in Azure and AWS. Looking for roles involving cloud transformation."
        },
        {
            "id": 12,
            "name": "Aisha Khan",
            "email": "aisha.khan@email.com",
            "phone": "+91-98765-43221",
            "location": "Pune",
            "experience_years": 3,
            "current_role": "Data Analyst",
            "company": "Deloitte",
            "skills": ["python", "sql", "tableau", "power bi", "excel", "data analysis"],
            "education": "B.Com",
            "current_salary": "8L",
            "notice_period": "30 days",
            "bio": "Data analyst with strong analytical skills. Looking to transition into data science roles."
        },
        {
            "id": 13,
            "name": "Nikhil Chandra",
            "email": "nikhil.chandra@email.com",
            "phone": "+91-98765-43222",
            "location": "Bangalore",
            "experience_years": 7,
            "current_role": "Senior Data Engineer",
            "company": "Netflix",
            "skills": ["spark", "python", "data engineering", "etl", "postgresql", "aws"],
            "education": "M.Tech",
            "current_salary": "35L",
            "notice_period": "45 days",
            "bio": "Data engineer with expertise in building data pipelines. Interested in working with big data technologies."
        },
        {
            "id": 14,
            "name": "Riya Agarwal",
            "email": "riya.agarwal@email.com",
            "phone": "+91-98765-43223",
            "location": "Jaipur",
            "experience_years": 2,
            "current_role": "Python Developer",
            "company": "Zomato",
            "skills": ["python", "django", "flask", "mysql", "docker"],
            "education": "B.Tech",
            "current_salary": "7L",
            "notice_period": "15 days",
            "bio": "Python developer with Django experience. Looking for opportunities in food-tech industry."
        },
        {
            "id": 15,
            "name": "Aditya Mishra",
            "email": "aditya.mishra@email.com",
            "phone": "+91-98765-43224",
            "location": "Noida",
            "experience_years": 5,
            "current_role": "ML Engineer",
            "company": "Paytm",
            "skills": ["python", "tensorflow", "machine learning", "deep learning", "nlp", "computer vision"],
            "education": "M.Tech",
            "current_salary": "24L",
            "notice_period": "30 days",
            "bio": "ML engineer passionate about AI/ML. Looking for roles involving cutting-edge AI applications."
        }
    ]
    
    return candidates